# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisualizer', '0002_auto_20170927_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluhyper',
            name='contIndex',
            field=models.FloatField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='aluhyper',
            name='AVG_Norm',
            field=models.FloatField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='aluhyper',
            name='SampleType',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
