# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisualizer', '0004_auto_20170928_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluhyper',
            name='SampleCode',
            field=models.IntegerField(),
        ),
    ]
