# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisualizer', '0005_auto_20170928_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluhyper',
            name='AVG_Norm',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=100),
        ),
        migrations.AlterField(
            model_name='aluhyper',
            name='SampleCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluhyper',
            name='SampleType',
            field=models.DecimalField(decimal_places=5, default='NA', max_digits=100),
        ),
        migrations.AlterField(
            model_name='aluhyper',
            name='contIndex',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=100),
        ),
    ]
