# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisualizer', '0006_auto_20170928_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluhyper',
            name='SampleType',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
